CREATE TABLE ORDERS(
    ID NUMBER,
    CONSTRAINT ORDER_PK PRIMARY KEY (ID),
    USER_ID NUMBER,
    CONSTRAINT USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    ROOM_ID NUMBER,
    CONSTRAINT ROOM_FK FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ID),
    DATE_FROM DATE,
    DATE_TO DATE,
    PRICE FLOAT
);