CREATE TABLE ROOMS(
    ID NUMBER,
    CONSTRAINT ROOMS_PK PRIMARY KEY(ID),
    NUMBER_OF_GUESTS NUMBER,
    PRICE FLOAT,
    BREAKFEST_INCLUDED NUMBER(1),
    PETS_ALLOWED NUMBER(1),
    AVAILABLE_FROM DATE,
    HOTEL_ID NUMBER,
    CONSTRAINT HOTEL_FK FOREIGN KEY (HOTEL_ID) REFERENCES HOTELS(ID)
);